site_name: Regionaler KI-Newsletter (DE) – Projekt-Bibel
site_url: https://timrost.github.io/newsletter-bibel/
repo_url: https://github.com/timrost/newsletter-bibel
edit_uri: edit/main/docs/

theme:
  name: material
  language: de
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

nav:
  - Übersicht: index.md
  - Projekt:
      - Ziele & Roadmap: overview/roadmap.md
      - Glossar: overview/glossar.md
  - Recherche:
      - Recht & Compliance (Master): research/recht-master-2025-09-04.md
      - Recht & Compliance (DE/EU): research/recht.md
      - Quellen & Discovery: research/quellen.md
  - Architektur:
      - Systemübersicht: architecture/overview.md
      - Datenmodell: architecture/data.md
  - How-tos:
      - Setup Hannover MVP: howto/setup-hannover.md
      - Newsletter-Versand: howto/newsletter.md
  - Reference:
      - APIs & Schnittstellen: reference/apis.md
  - Entscheidungen (ADR):
      - ADR-0001 Hosting-Strategie: adr/0001-hosting-strategie.md
      - ADR-0002 Snippet/Teaser-Policy: adr/0002-snippet-policy.md
      - ADR-0003 Geo-Aboutness/Region-Scoring: adr/ADR-0003-geo-aboutness-region-scoring.md
      - ADR-0004 Bild-Policy (Proposed): adr/ADR-0004-bild-policy.md
  - Runbooks:
      - Newsletter – DOI/Impressum/Tracking (Master): runbooks/newsletter-compliance-runbook-master-2025-09-04.md
      - Phase 2 Readme: runbooks/phase2-readme.md
      - Pilotplan Phase 2: runbooks/phase2-pilot.md
  - Specs:
      - Übersicht: specs/index.md
      - Article Schema: specs/article.schema.json
      - SourceProfile Schema: specs/sourceprofile.schema.json
      - ConsentLog Schema: specs/consentlog.schema.json
      - Newsletter Beispiel: specs/newsletter.example.json
  - Flows:
    - Übersicht: flows/README.md
    - Ingest (Loop Feeds → articles.json): flows/n8n-phase2-ingest-loop-feeds.json
    - Export (?region=…): flows/n8n-phase2-export-by-region.json
    - Discovery (Seeds → feeds.json): flows/n8n-phase2-discovery-seeds-to-feeds.json
    - LEGACY – Ingest (Single-Feed): flows/n8n-phase2-ingest.json
    - LEGACY – Ingest (MVP Hannover): flows/n8n-phase2-ingest-mvp-hannover.json
    - LEGACY – Export (ohne Region): flows/n8n-phase2-export.json
  - Scripts:
      - Übersicht: scripts/README.md
      - GitHub Commit Step: scripts/github-commit-step.md
  - Sprints:
      - Sprint 1 (Recht & Architektur): sprints/sprint1.md
      - Sprint 2 (Hannover MVP): sprints/sprint2.md
  - Impressum: impressum.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/timrost/newsletter-bibel

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - search

